### ISSUE TITLE
Typing problem in `signal2` in the Readme server example code

### ISSUE THREAD

**Issue by sth** [ccxtechnologies/adbus#52]
I try to run the following code (a shortened version of the server example from the Readme):

```python
import adbus
import typing

class ExampleClass(adbus.server.Object):
    signal2: typing.List[int] = adbus.server.Signal()
```

This results in an exception:
```
Traceback (most recent call last):
  File "/home/sth/src/screenwatch-1/.venv/lib/python3.7/site-packages/adbus-1.0.1-py3.7-linux-x86_64.egg/adbus/server/signal.py", line 59, in __set_name__
    self.dbus_signature = [sdbus.dbus_signature(s) for s in signature]
  File "/home/sth/src/screenwatch-1/.venv/lib/python3.7/site-packages/adbus-1.0.1-py3.7-linux-x86_64.egg/adbus/server/signal.py", line 59, in <listcomp>
    self.dbus_signature = [sdbus.dbus_signature(s) for s in signature]
  File "/usr/lib/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.7/typing.py", line 626, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.7/typing.py", line 626, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.7/typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ex1.py", line 4, in <module>
    class ExampleClass(adbus.server.Object):
RuntimeError: Error calling __set_name__ on 'Signal' instance 'signal2' in 'ExampleClass'
```

**Comment by charleseidsness** [comment]
This looks like it's a new issue on Python version 3.7.

iterator(typing.List[int]) returns a valid iterator, but then when you try to iterate through it it throws up that error.

We were expecting a TypeError on iterator(typing.List[int]) because we shouldn't be able to create an iterator from it. The Python folks are doing some good work on moving away from the typing library which is a bit of a hacky thing, but I imagine that's a couple dot releases away.

For now I'll try to add a workaround for this case.
