### ISSUE TITLE
Exception caused by typing issue when running example code

### ISSUE THREAD

**Issue by andysan** [ccxtechnologies/adbus#70]
Running the following code from #52 produces an exception similar to the original ticket on Python 3.8 and adbus 1.1.3:
```
import adbus
import typing

class ExampleClass(adbus.server.Object):
    signal2: typing.List[int] = adbus.server.Signal()
```
This is the exception:
```
Traceback (most recent call last):
  File "[VIRTUAL_ENV]/python/lib/python3.8/site-packages/adbus/server/signal.py", line 63, in __set_name__
    self.dbus_signature = [
  File "[VIRTUAL_ENV]/python3.8/site-packages/adbus/server/signal.py", line 63, in <listcomp>
    self.dbus_signature = [
  File "/usr/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 682, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.8/typing.py", line 682, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    class ExampleClass(adbus.server.Object):
RuntimeError: Error calling __set_name__ on 'Signal' instance 'signal2' in 'ExampleClass'
```
The exception above was produced in a Python 3.8 installation from Ubuntu 18.04 running in a virtual environment. I tried to upgrade the `typing` package, but that didn't seem to make any difference.

**Comment by charleseidsness** [comment]
I just checked-in  f4612c8 which should fix this for you. If it does let me know and I can create a new release.

Thanks for reporting this!

**Comment by charleseidsness** [comment]
Haven't heard back so assume it is closed. Will create a new release.
