### ISSUE TITLE
Cython compile type errors when trying to install adbus

### ISSUE THREAD

**Issue by laped83** [ccxtechnologies/adbus#78]
On Fedora 39 I get the following error when trying to install adbus.

Python 3.12.1
Cython 3.0.8

```
❯ pip3 install adbus
Defaulting to user installation because normal site-packages is not writeable
Collecting adbus
  Using cached adbus-1.2.0.tar.gz (196 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              if unprivileged:
                  self.flags |= sdbus_h.SD_BUS_VTABLE_UNPRIVILEGED
      
              self.x.member = self.name
              self.x.handler = method_message_handler
                               ^
      ------------------------------------------------------------
      
      adbus/sdbus/method.pxi:87:25: Cannot assign type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1' to 'sd_bus_message_handler_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              if emits_invalidation:
                  self.flags |= sdbus_h.SD_BUS_VTABLE_PROPERTY_EMITS_INVALIDATION
      
              self.x.member = self.name
              self.x.get = property_get_handler
                           ^
      ------------------------------------------------------------
      
      adbus/sdbus/property.pxi:117:21: Cannot assign type 'int (sd_bus *, const char *, const char *, const char *, sd_bus_message *, void *, sd_bus_error *) except? -1' to 'sd_bus_property_get_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (sd_bus *, const char *, const char *, const char *, sd_bus_message *, void *, sd_bus_error *) except? -1'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.flags |= sdbus_h.SD_BUS_VTABLE_PROPERTY_EMITS_INVALIDATION
      
              self.x.member = self.name
              self.x.get = property_get_handler
              if not read_only:
                  self.x.set = property_set_handler
                               ^
      ------------------------------------------------------------
      
      adbus/sdbus/property.pxi:119:25: Cannot assign type 'int (sd_bus *, const char *, const char *, const char *, sd_bus_message *, void *, sd_bus_error *) except? -1' to 'sd_bus_property_set_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (sd_bus *, const char *, const char *, const char *, sd_bus_message *, void *, sd_bus_error *) except? -1'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              cdef int ret
              self.event.clear()
      
              Py_INCREF(self)
              ret = sdbus_h.sd_bus_call_async(self.service.bus, NULL,
                      self.message.message, call_callback, <void *>self,
                                            ^
      ------------------------------------------------------------
      
      adbus/sdbus/call.pxi:60:38: Cannot assign type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1' to 'sd_bus_message_handler_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.signature = signature
              self.loop = service.loop
              self.seperate_arguments = seperate_arguments
      
              ret = sdbus_h.sd_bus_add_match(service.bus, &self._slot, self.match,
                  listen_message_handler, <void *>self)
                  ^
      ------------------------------------------------------------
      
      adbus/sdbus/listen.pxi:45:12: Cannot assign type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1' to 'sd_bus_message_handler_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (sd_bus_message *, void *, sd_bus_error *) except? -1'.
      Compiling adbus/sdbus.pyx because it changed.
      [1/1] Cythonizing adbus/sdbus.pyx
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iras11gj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iras11gj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-iras11gj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-iras11gj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 31, in <module>
        File "/tmp/pip-build-env-iras11gj/overlay/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-iras11gj/overlay/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: adbus/sdbus.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by charleseidsness** [comment]
I think this was because the version on PyPi was behind the latest version in this repo and was missing: https://github.com/ccxtechnologies/adbus/commit/1804484f3d8998254be398d5154bf8b48ed5f7a5. I just updated PyPi to be inline with the latest release for this repo.

Hopefully that resolves this issue.

**Comment by laped83** [comment]
Thanks. This solves the issue :+1:
